Made a number or improvements and expanded testing
DeanoDee/endpointGallery pull request #3
Opened 2017-03-17 16:49 UTC by DeanoDee

2017-03-17 17:36 UTC, Mackarous commented
It's hard to see what's changed. Is it mostly renaming and moving things?

2017-03-17 17:40 UTC, DeanoDee commented
the changes are 
let to const (prefer const a best practice I was on the fence about until recently)
moved the components to components folder
moved html out of app into display components
enhanced tests

please treat the components as new, as I didn't have you guys reviewing this early on.

2017-03-17 17:49 UTC, Mackarous requested changes

2017-03-17 17:49 UTC, Mackarous commented on src/components/App/index.jsx
> +			<ImageCard key={_id} imageObject={imageObject}/>
if the `ImageCard` component is taking in the key which is a param in `imageObject`, would it still work if you just forward the `imageObject` through?

2017-03-17 18:01 UTC, DeanoDee commented on src/components/App/index.jsx
> +			<ImageCard key={_id} imageObject={imageObject}/>
This isn't passed to image card, the key is something React uses to deal with looped identification

2017-03-17 18:02 UTC, Mackarous approved these changes

2017-03-18 01:33 UTC, DeanoDee commented
@Mackarous can you take a look at my last commit? added one more thing

2017-03-19 15:20 UTC, Mackarous commented
@DeanoDee Looks cool! You can set hard requirements with PropTypes? What happens if they aren't met?

2017-03-19 15:53 UTC, DeanoDee commented
It throws an error

2017-03-20 21:02 UTC, a-mehta commented on src/components/endpointEntry/index.jsx
> +		const {show:currentShow} = this.state;
Is there a reason why this can't be `const {currentShow} = this.state;`?

2017-03-20 21:05 UTC, a-mehta commented on src/components/imageCard/index.jsx
> +	const maxTextLength = 78;
Is this pixels? Characters?

2017-03-20 21:06 UTC, a-mehta commented on src/components/App/index.test.js
> +		const getCards = jest.fn();
What is `jest`?

2017-03-20 21:07 UTC, a-mehta commented on src/components/App/index.test.js
> +		expect(tree).toMatchSnapshot();
What is the aforementioned snapshot?

2017-03-20 21:14 UTC, DeanoDee commented on src/components/endpointEntry/index.jsx
> +		const {show:currentShow} = this.state;
you know

2017-03-20 21:15 UTC, DeanoDee commented on src/components/imageCard/index.jsx
> +	const maxTextLength = 78;
will do

2017-03-21 02:12 UTC, DeanoDee commented on src/components/imageCard/index.jsx
> +	const maxTextLength = 78;
@a-mehta, it's done

2017-03-21 02:12 UTC, DeanoDee commented on src/components/App/index.test.js
> +		const getCards = jest.fn();
we chatted

2017-03-21 02:12 UTC, DeanoDee commented on src/components/App/index.test.js
> +		expect(tree).toMatchSnapshot();
we chatted

2017-03-21 18:00 UTC, DeanoDee commented
@a-mehta if you like merge it

2017-03-22 15:32 UTC, merged